name: "Package"

on:
  push:
    tags:
      - v*

jobs:
  publish_to_pypi:
    name: 📦 Publish to PyPi
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
      - name: 🐍 Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ⬇️ Install dependencies
        run: python -m pip install build --user
      - name: 🏗️ Build
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: 🚀 Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
