name: "Test Python"

on:
  push:
    paths-ignore:
    - 'docs/**'

# Our test suite should cover:
# - Compatibility with the most recent versions of Python, Wagtail and Django
# - at least one test run for older supported version of Python, Wagtail and Django
# - a test run against Django's git main branch (allowing failures)
# - a test run against Wagtail's git main branch (allowing failures)

# Current configuration:
# - python 3.9, django 4, wagtail 4 (+ linting and other checks)
# - python 3.8, django 3.2, wagtail 3
# - python 3.7, django 3.1, wagtail 2.16

jobs:
  test-current:
    name: With latest stable dependencies
    env:
      DJANGO_SETTINGS_MODULE: wagtailpurge.testapp.settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ⬇️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Django>=4,<5"
          pip install "Wagtail>=4,<5"
          pip install -e .[test]
      - name: ✅ Check for missing migrations
        run: django-admin makemigrations --check --noinput
      - name: 🪣 Collect static files
        run: django-admin collectstatic
      - name: 🧪 Run tests
        run: pytest --junitxml=junit/test-results.xml --cov=wagtailpurge

  test-legacy:
    name: With older dependencies
    needs: test-current
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: wagtailpurge.testapp.settings
    strategy:
      matrix:
        include:
          - python: 3.8
            wagtail: "Wagtail>=3,<4"
            django: Django>=4,<5
          - python: 3.7
            wagtail: "Wagtail>=2,<3"
            django: Django>=3.2,<3.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: ⬇️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
          pip install -e .[test]
      - name: 🪣 Collect static files
        run: django-admin collectstatic
      - name: 🧪 Run tests
        run: pytest

  test-latest:
    name: With main Django/Wagtail branches
    needs: test-legacy
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DJANGO_SETTINGS_MODULE: wagtailpurge.testapp.settings
    strategy:
      matrix:
        include:
          - django: "git+https://github.com/django/django.git@main#egg=Django"
            wagtail: Wagtail>=4,<5
          - django: Django>=4,<5
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ⬇️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: 🪣 Collect static files
        run: django-admin collectstatic
      - name: 🧪 Run tests
        run: pytest
