name: "Test (experimental)"

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test Python 🐍 with main Django/Wagtail branches
    env:
      DJANGO_SETTINGS_MODULE: wagtailpurge.tests.settings
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - django: "git+https://github.com/django/django.git@main#egg=Django"
            wagtail: Wagtail>=2.14,<2.15
          - django: Django>=3.2,<3.3
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail"
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
      - name: ⚙️ Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ⬇️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: 🪣 Collect static files
        run: django-admin collectstatic
      - name: 🧪 Run tests
        run: pytest
